# Migration Reorder Script - Fix Dependency Order
# Generated by Sonnet (The Coder)

$migrations = @{
    "2024_11_01_000001_create_branches_table.php" = "2024_11_01_000001_create_branches_table.php"
    "2024_11_01_000002_create_roles_table.php" = "2024_11_01_000002_create_roles_table.php"
    "2024_11_01_000003_create_permissions_table.php" = "2024_11_01_000003_create_permissions_table.php"
    "2024_11_01_000004_create_role_permissions_table.php" = "2024_11_01_000004_create_role_permissions_table.php"
    "2024_11_01_000005_add_role_id_to_users_table.php" = "2024_11_01_000005_add_role_id_to_users_table.php"
    "2024_11_01_000006_create_patients_table.php" = "2024_11_01_000006_create_patients_table.php"
    "2024_11_01_000012_create_services_table.php" = "2024_11_01_000007_create_services_table.php"
    "2024_11_01_000007_create_opd_records_table.php" = "2024_11_01_000008_create_opd_records_table.php"
    "2024_11_01_000008_create_patient_notes_table.php" = "2024_11_01_000009_create_patient_notes_table.php"
    "2024_11_01_000009_create_appointments_table.php" = "2024_11_01_000010_create_appointments_table.php"
    "2024_11_01_000014_create_course_packages_table.php" = "2024_11_01_000011_create_course_packages_table.php"
    "2024_11_01_000013_create_pt_service_rates_table.php" = "2024_11_01_000012_create_pt_service_rates_table.php"
    "2024_11_01_000032_create_staff_table.php" = "2024_11_01_000013_create_staff_table.php"
    "2024_11_01_000010_create_queues_table.php" = "2024_11_01_000014_create_queues_table.php"
    "2024_11_01_000011_create_confirmation_lists_table.php" = "2024_11_01_000015_create_confirmation_lists_table.php"
    "2024_11_01_000015_create_commission_rates_table.php" = "2024_11_01_000016_create_commission_rates_table.php"
    "2024_11_01_000018_create_pt_requests_table.php" = "2024_11_01_000017_create_pt_requests_table.php"
    "2024_11_01_000033_create_schedules_table.php" = "2024_11_01_000018_create_schedules_table.php"
    "2024_11_01_000034_create_leave_requests_table.php" = "2024_11_01_000019_create_leave_requests_table.php"
    "2024_11_01_000035_create_evaluations_table.php" = "2024_11_01_000020_create_evaluations_table.php"
    "2024_11_01_000020_create_invoices_table.php" = "2024_11_01_000021_create_invoices_table.php"
    "2024_11_01_000041_create_loyalty_points_table.php" = "2024_11_01_000022_create_loyalty_points_table.php"
    "2024_11_01_000037_create_equipment_table.php" = "2024_11_01_000023_create_equipment_table.php"
    "2024_11_01_000039_create_stock_items_table.php" = "2024_11_01_000024_create_stock_items_table.php"
    "2024_11_01_000016_create_treatments_table.php" = "2024_11_01_000025_create_treatments_table.php"
    "2024_11_01_000022_create_payments_table.php" = "2024_11_01_000026_create_payments_table.php"
    "2024_11_01_000025_create_course_purchases_table.php" = "2024_11_01_000027_create_course_purchases_table.php"
    "2024_11_01_000043_create_loyalty_rewards_table.php" = "2024_11_01_000028_create_loyalty_rewards_table.php"
    "2024_11_01_000038_create_maintenance_logs_table.php" = "2024_11_01_000029_create_maintenance_logs_table.php"
    "2024_11_01_000017_create_treatment_audit_logs_table.php" = "2024_11_01_000030_create_treatment_audit_logs_table.php"
    "2024_11_01_000019_create_follow_up_lists_table.php" = "2024_11_01_000031_create_follow_up_lists_table.php"
    "2024_11_01_000021_create_invoice_items_table.php" = "2024_11_01_000032_create_invoice_items_table.php"
    "2024_11_01_000023_create_documents_table.php" = "2024_11_01_000033_create_documents_table.php"
    "2024_11_01_000026_create_course_usage_logs_table.php" = "2024_11_01_000034_create_course_usage_logs_table.php"
    "2024_11_01_000027_create_course_sharing_table.php" = "2024_11_01_000035_create_course_sharing_table.php"
    "2024_11_01_000042_create_loyalty_transactions_table.php" = "2024_11_01_000036_create_loyalty_transactions_table.php"
    "2024_11_01_000040_create_stock_transactions_table.php" = "2024_11_01_000037_create_stock_transactions_table.php"
    "2024_11_01_000024_create_refunds_table.php" = "2024_11_01_000038_create_refunds_table.php"
    "2024_11_01_000028_create_course_renewals_table.php" = "2024_11_01_000039_create_course_renewals_table.php"
    "2024_11_01_000036_create_pt_replacements_table.php" = "2024_11_01_000040_create_pt_replacements_table.php"
    "2024_11_01_000029_create_commissions_table.php" = "2024_11_01_000041_create_commissions_table.php"
    "2024_11_01_000030_create_df_payments_table.php" = "2024_11_01_000042_create_df_payments_table.php"
    "2024_11_01_000031_create_commission_splits_table.php" = "2024_11_01_000043_create_commission_splits_table.php"
    "2024_11_01_000044_create_audit_logs_table.php" = "2024_11_01_000044_create_audit_logs_table.php"
    "2024_11_01_000045_create_notifications_table.php" = "2024_11_01_000045_create_notifications_table.php"
}

Write-Host "Starting migration reorder..." -ForegroundColor Cyan

# Step 1: Rename to temp names
foreach ($old in $migrations.Keys) {
    if (Test-Path $old) {
        $temp = "$old.tmp"
        Rename-Item -Path $old -NewName $temp
        Write-Host "  Temp: $old -> $temp" -ForegroundColor Yellow
    }
}

# Step 2: Rename from temp to final
foreach ($old in $migrations.Keys) {
    $temp = "$old.tmp"
    $new = $migrations[$old]
    if (Test-Path $temp) {
        Rename-Item -Path $temp -NewName $new
        Write-Host "  Final: $temp -> $new" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "Migration reorder completed successfully!" -ForegroundColor Green
$count = $migrations.Count
Write-Host "Total files processed: $count" -ForegroundColor Cyan
